# Generated by Django 3.2.10 on 2022-01-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booksinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Author', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
