# Generated by Django 3.2.10 on 2022-01-13 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booksinfo',
            name='date',
        ),
    ]
